version: '3'

services:

  db:
    image: "postgres"
    restart: "always"
    container_name: "postgres_pidb"
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: "pass1234"
      POSTGRES_USER: "dbuser"
      POSTGRES_DB: "master"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
     - "postgres"
     
#nginx server
  www:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "8081:80"
      #- "443:443"
    volumes:
      - /home/haroldo/git/nginx-postgress-docker/www: /usr/share:ro

networks:

  postgres:
    driver: "bridge"


networks:

  postgres:
    driver: "bridge"

volumes:
  postgres_data:
